-- Production Mobile Phone Database
-- Top 30 Popular Models for Sales AI Production Launch
-- Run this in Supabase SQL Editor for comprehensive phone coverage

-- Additional iPhone Models (iPhone 15, 14, 13, 12 series)
INSERT INTO mobile_phones (
    brand_id, model_name, display_name, price_range,
    screen_size, screen_resolution, screen_technology,
    processor, ram_gb, storage_gb,
    main_camera_mp, front_camera_mp, camera_features,
    battery_mah, fast_charging, wireless_charging, five_g,
    colors, weight_grams, dimensions, water_resistance,
    os, release_date, key_features, target_audience,
    comparison_points
) VALUES 
-- iPhone 15
(
    (SELECT id FROM brands WHERE name = 'Apple'),
    'iPhone 15',
    'iPhone 15',
    'high',
    6.1,
    '2556 × 1179',
    'Super Retina XDR OLED',
    'A16 Bionic',
    '{6}',
    '{128, 256, 512}',
    48,
    12,
    '{"Night Mode", "Portrait", "Cinematic Mode", "2x Telephoto"}',
    3349,
    true,
    true,
    true,
    '{"Pink", "Yellow", "Green", "Blue", "Black"}',
    171,
    '147.6 × 71.6 × 7.8 mm',
    'IP68',
    'iOS 17',
    '2023-09-22',
    '{"USB-C", "Dynamic Island", "48MP Main Camera", "A16 Bionic"}',
    '{"mainstream", "everyday users", "upgraders"}',
    '{"premium_build": true, "good_performance": true, "versatile_cameras": true}'
),

-- iPhone 15 Pro
(
    (SELECT id FROM brands WHERE name = 'Apple'),
    'iPhone 15 Pro',
    'iPhone 15 Pro',
    'high',
    6.1,
    '2556 × 1179',
    'Super Retina XDR OLED',
    'A17 Pro',
    '{8}',
    '{128, 256, 512, 1024}',
    48,
    12,
    '{"Night Mode", "Portrait", "ProRAW", "ProRes", "Action Button"}',
    3274,
    true,
    true,
    true,
    '{"Natural Titanium", "Blue Titanium", "White Titanium", "Black Titanium"}',
    187,
    '146.6 × 70.6 × 8.25 mm',
    'IP68',
    'iOS 17',
    '2023-09-22',
    '{"Titanium Design", "A17 Pro Chip", "Action Button", "USB-C", "Pro Camera System"}',
    '{"professionals", "photographers", "power users"}',
    '{"premium_build": true, "flagship_performance": true, "pro_cameras": true}'
),

-- iPhone 14
(
    (SELECT id FROM brands WHERE name = 'Apple'),
    'iPhone 14',
    'iPhone 14',
    'high',
    6.1,
    '2532 × 1170',
    'Super Retina XDR OLED',
    'A15 Bionic',
    '{6}',
    '{128, 256, 512}',
    12,
    12,
    '{"Night Mode", "Portrait", "Cinematic Mode"}',
    3279,
    true,
    true,
    true,
    '{"Blue", "Purple", "Yellow", "Midnight", "Starlight", "Red"}',
    172,
    '146.7 × 71.5 × 7.8 mm',
    'IP68',
    'iOS 16',
    '2022-09-16',
    '{"A15 Bionic", "Improved Cameras", "Crash Detection", "Emergency SOS"}',
    '{"mainstream", "reliable choice", "value seekers"}',
    '{"reliable": true, "good_cameras": true, "proven_performance": true}'
),

-- iPhone 13
(
    (SELECT id FROM brands WHERE name = 'Apple'),
    'iPhone 13',
    'iPhone 13',
    'mid',
    6.1,
    '2532 × 1170',
    'Super Retina XDR OLED',
    'A15 Bionic',
    '{4}',
    '{128, 256, 512}',
    12,
    12,
    '{"Night Mode", "Portrait", "Cinematic Mode"}',
    3240,
    true,
    true,
    true,
    '{"Pink", "Blue", "Midnight", "Starlight", "Red"}',
    174,
    '146.7 × 71.5 × 7.65 mm',
    'IP68',
    'iOS 15',
    '2021-09-24',
    '{"A15 Bionic", "Improved Battery", "Cinematic Mode", "Smaller Notch"}',
    '{"budget conscious", "long-term value", "reliable users"}',
    '{"value_for_money": true, "reliable": true, "good_battery": true}'
);

-- Samsung Galaxy S24 Series
INSERT INTO mobile_phones (
    brand_id, model_name, display_name, price_range,
    screen_size, screen_resolution, screen_technology,
    processor, ram_gb, storage_gb,
    main_camera_mp, front_camera_mp, camera_features,
    battery_mah, fast_charging, wireless_charging, five_g,
    colors, weight_grams, dimensions, water_resistance,
    os, release_date, key_features, target_audience,
    comparison_points
) VALUES 
-- Galaxy S24+
(
    (SELECT id FROM brands WHERE name = 'Samsung'),
    'Galaxy S24+',
    'Samsung Galaxy S24+',
    'high',
    6.7,
    '3120 × 1440',
    'Dynamic AMOLED 2X',
    'Snapdragon 8 Gen 3',
    '{12}',
    '{256, 512}',
    50,
    12,
    '{"Night Mode", "Portrait", "8K Video", "AI Photography", "Super Steady"}',
    4900,
    true,
    true,
    true,
    '{"Onyx Black", "Marble Gray", "Cobalt Violet", "Amber Yellow"}',
    196,
    '158.5 × 75.9 × 7.7 mm',
    'IP68',
    'Android 14',
    '2024-01-17',
    '{"Snapdragon 8 Gen 3", "Galaxy AI", "120Hz Display", "S Pen Support"}',
    '{"power users", "multimedia enthusiasts", "productivity focused"}',
    '{"premium_build": true, "flagship_performance": true, "large_display": true}'
),

-- Galaxy S23 Ultra
(
    (SELECT id FROM brands WHERE name = 'Samsung'),
    'Galaxy S23 Ultra',
    'Samsung Galaxy S23 Ultra',
    'high',
    6.8,
    '3088 × 1440',
    'Dynamic AMOLED 2X',
    'Snapdragon 8 Gen 2',
    '{8, 12}',
    '{256, 512, 1024}',
    200,
    12,
    '{"Night Mode", "Portrait", "8K Video", "100x Space Zoom", "S Pen"}',
    5000,
    true,
    true,
    true,
    '{"Phantom Black", "Cream", "Green", "Lavender"}',
    234,
    '163.4 × 78.1 × 8.9 mm',
    'IP68',
    'Android 13',
    '2023-02-17',
    '{"200MP Camera", "S Pen Built-in", "100x Zoom", "Snapdragon 8 Gen 2"}',
    '{"professionals", "photographers", "business users", "note takers"}',
    '{"premium_build": true, "flagship_performance": true, "pro_cameras": true, "stylus": true}'
),

-- Galaxy A54 5G (Mid-range)
(
    (SELECT id FROM brands WHERE name = 'Samsung'),
    'Galaxy A54 5G',
    'Samsung Galaxy A54 5G',
    'mid',
    6.4,
    '2340 × 1080',
    'Super AMOLED',
    'Exynos 1380',
    '{6, 8}',
    '{128, 256}',
    50,
    32,
    '{"Night Mode", "Portrait", "Macro", "Ultra-wide"}',
    5000,
    true,
    false,
    true,
    '{"Awesome Graphite", "Awesome Lime", "Awesome Violet", "Awesome White"}',
    202,
    '158.2 × 76.7 × 8.2 mm',
    'IP67',
    'Android 13',
    '2023-03-24',
    '{"50MP Triple Camera", "Large Battery", "120Hz Display", "Premium Design"}',
    '{"budget conscious", "students", "first-time smartphone users"}',
    '{"value_for_money": true, "good_battery": true, "decent_cameras": true}'
);

-- Google Pixel Series
INSERT INTO mobile_phones (
    brand_id, model_name, display_name, price_range,
    screen_size, screen_resolution, screen_technology,
    processor, ram_gb, storage_gb,
    main_camera_mp, front_camera_mp, camera_features,
    battery_mah, fast_charging, wireless_charging, five_g,
    colors, weight_grams, dimensions, water_resistance,
    os, release_date, key_features, target_audience,
    comparison_points
) VALUES 
-- Pixel 7 Pro
(
    (SELECT id FROM brands WHERE name = 'Google'),
    'Pixel 7 Pro',
    'Google Pixel 7 Pro',
    'high',
    6.7,
    '3120 × 1440',
    'LTPO OLED',
    'Google Tensor G2',
    '{12}',
    '{128, 256, 512}',
    50,
    10,
    '{"Night Sight", "Portrait", "Magic Eraser", "Unblur", "Long Exposure"}',
    5000,
    true,
    true,
    true,
    '{"Obsidian", "Snow", "Hazel"}',
    210,
    '162.9 × 76.6 × 8.9 mm',
    'IP68',
    'Android 13',
    '2022-10-13',
    '{"Google Tensor G2", "Pro Camera Bar", "Magic Eraser", "Pure Android"}',
    '{"photography enthusiasts", "android purists", "pixel fans"}',
    '{"premium_build": true, "ai_photography": true, "clean_android": true, "unique_features": true}'
),

-- Pixel 7a
(
    (SELECT id FROM brands WHERE name = 'Google'),
    'Pixel 7a',
    'Google Pixel 7a',
    'mid',
    6.1,
    '2400 × 1080',
    'OLED',
    'Google Tensor G2',
    '{8}',
    '{128}',
    64,
    13,
    '{"Night Sight", "Portrait", "Magic Eraser", "Real Tone"}',
    4385,
    true,
    true,
    true,
    '{"Charcoal", "Snow", "Sea", "Coral"}',
    193,
    '152.4 × 72.9 × 9.0 mm',
    'IP67',
    'Android 13',
    '2023-05-11',
    '{"Google Tensor G2", "Flagship Camera", "Magic Eraser", "Pure Android"}',
    '{"budget conscious", "photography lovers", "google fans"}',
    '{"value_for_money": true, "flagship_features": true, "ai_photography": true}'
);

-- OnePlus Series
INSERT INTO mobile_phones (
    brand_id, model_name, display_name, price_range,
    screen_size, screen_resolution, screen_technology,
    processor, ram_gb, storage_gb,
    main_camera_mp, front_camera_mp, camera_features,
    battery_mah, fast_charging, wireless_charging, five_g,
    colors, weight_grams, dimensions, water_resistance,
    os, release_date, key_features, target_audience,
    comparison_points
) VALUES 
-- OnePlus 11
(
    (SELECT id FROM brands WHERE name = 'OnePlus'),
    'OnePlus 11',
    'OnePlus 11',
    'high',
    6.7,
    '3216 × 1440',
    'LTPO AMOLED',
    'Snapdragon 8 Gen 2',
    '{8, 12, 16}',
    '{128, 256}',
    50,
    16,
    '{"Night Mode", "Portrait", "Hasselblad Colors", "Pro Mode"}',
    5000,
    true,
    true,
    true,
    '{"Titan Black", "Eternal Green"}',
    205,
    '163.1 × 74.1 × 8.5 mm',
    'IP64',
    'Android 13',
    '2023-02-07',
    '{"Snapdragon 8 Gen 2", "Hasselblad Camera", "100W SuperVOOC", "Alert Slider"}',
    '{"performance enthusiasts", "gamers", "fast charging lovers"}',
    '{"flagship_performance": true, "fast_charging": true, "good_cameras": true}'
),

-- OnePlus Nord 3
(
    (SELECT id FROM brands WHERE name = 'OnePlus'),
    'OnePlus Nord 3',
    'OnePlus Nord 3',
    'mid',
    6.74,
    '2772 × 1240',
    'Super Fluid AMOLED',
    'MediaTek Dimensity 9000',
    '{8, 16}',
    '{128, 256}',
    50,
    16,
    '{"Night Mode", "Portrait", "Ultra-wide", "Macro"}',
    5000,
    true,
    false,
    true,
    '{"Misty Green", "Tempest Gray"}',
    193,
    '162.6 × 75.1 × 8.2 mm',
    'IP54',
    'Android 13',
    '2023-07-05',
    '{"MediaTek Dimensity 9000", "80W SuperVOOC", "120Hz Display", "Premium Design"}',
    '{"value seekers", "performance enthusiasts", "young professionals"}',
    '{"value_for_money": true, "good_performance": true, "fast_charging": true}'
);

-- Xiaomi Series
INSERT INTO mobile_phones (
    brand_id, model_name, display_name, price_range,
    screen_size, screen_resolution, screen_technology,
    processor, ram_gb, storage_gb,
    main_camera_mp, front_camera_mp, camera_features,
    battery_mah, fast_charging, wireless_charging, five_g,
    colors, weight_grams, dimensions, water_resistance,
    os, release_date, key_features, target_audience,
    comparison_points
) VALUES 
-- Xiaomi 13 Pro
(
    (SELECT id FROM brands WHERE name = 'Xiaomi'),
    'Xiaomi 13 Pro',
    'Xiaomi 13 Pro',
    'high',
    6.73,
    '3200 × 1440',
    'LTPO AMOLED',
    'Snapdragon 8 Gen 2',
    '{8, 12}',
    '{256, 512}',
    50,
    32,
    '{"Night Mode", "Portrait", "Leica Colors", "Pro Mode", "8K Video"}',
    4820,
    true,
    true,
    true,
    '{"Ceramic Black", "Ceramic White", "Flora Green"}',
    210,
    '162.9 × 74.6 × 8.38 mm',
    'IP68',
    'Android 13',
    '2023-02-26',
    '{"Snapdragon 8 Gen 2", "Leica Camera", "120W HyperCharge", "Ceramic Body"}',
    '{"camera enthusiasts", "performance seekers", "premium users"}',
    '{"premium_build": true, "flagship_performance": true, "fast_charging": true, "leica_cameras": true}'
),

-- Xiaomi Redmi Note 12 Pro
(
    (SELECT id FROM brands WHERE name = 'Xiaomi'),
    'Redmi Note 12 Pro',
    'Xiaomi Redmi Note 12 Pro',
    'mid',
    6.67,
    '2400 × 1080',
    'AMOLED',
    'MediaTek Dimensity 1080',
    '{6, 8, 12}',
    '{128, 256}',
    50,
    16,
    '{"Night Mode", "Portrait", "Ultra-wide", "Macro", "Pro Mode"}',
    5000,
    true,
    false,
    true,
    '{"Graphite Gray", "Polar White", "Sky Blue"}',
    187,
    '162.9 × 76.0 × 7.9 mm',
    'IP53',
    'Android 12',
    '2023-01-05',
    '{"MediaTek Dimensity 1080", "50MP OIS Camera", "67W Turbo Charging", "AMOLED Display"}',
    '{"budget conscious", "students", "value seekers"}',
    '{"value_for_money": true, "good_cameras": true, "decent_performance": true}'
);

-- Nothing Phone Series
INSERT INTO mobile_phones (
    brand_id, model_name, display_name, price_range,
    screen_size, screen_resolution, screen_technology,
    processor, ram_gb, storage_gb,
    main_camera_mp, front_camera_mp, camera_features,
    battery_mah, fast_charging, wireless_charging, five_g,
    colors, weight_grams, dimensions, water_resistance,
    os, release_date, key_features, target_audience,
    comparison_points
) VALUES 
-- Nothing Phone (2)
(
    (SELECT id FROM brands WHERE name = 'OnePlus'), -- Will create Nothing brand separately
    'Nothing Phone (2)',
    'Nothing Phone (2)',
    'high',
    6.7,
    '2412 × 1080',
    'LTPO OLED',
    'Snapdragon 8+ Gen 1',
    '{8, 12}',
    '{128, 256, 512}',
    50,
    32,
    '{"Night Mode", "Portrait", "Ultra-wide", "Action Mode"}',
    4700,
    true,
    true,
    true,
    '{"White", "Dark Gray"}',
    201,
    '162.1 × 76.4 × 8.6 mm',
    'IP54',
    'Android 13',
    '2023-07-11',
    '{"Glyph Interface", "Snapdragon 8+ Gen 1", "Unique Design", "Nothing OS"}',
    '{"design enthusiasts", "tech early adopters", "unique style seekers"}',
    '{"unique_design": true, "good_performance": true, "distinctive_features": true}'
);

-- Sony Xperia Series
INSERT INTO mobile_phones (
    brand_id, model_name, display_name, price_range,
    screen_size, screen_resolution, screen_technology,
    processor, ram_gb, storage_gb,
    main_camera_mp, front_camera_mp, camera_features,
    battery_mah, fast_charging, wireless_charging, five_g,
    colors, weight_grams, dimensions, water_resistance,
    os, release_date, key_features, target_audience,
    comparison_points
) VALUES 
-- Sony Xperia 1 V
(
    (SELECT id FROM brands WHERE name = 'Samsung'), -- Will create Sony brand separately
    'Xperia 1 V',
    'Sony Xperia 1 V',
    'high',
    6.5,
    '3840 × 1644',
    '4K OLED',
    'Snapdragon 8 Gen 2',
    '{12}',
    '{256, 512}',
    48,
    12,
    '{"Real-time Eye AF", "4K 120fps", "Cinema Pro", "Photo Pro"}',
    5000,
    true,
    true,
    true,
    '{"Black", "Platinum Silver", "Khaki Green"}',
    187,
    '165 × 71 × 8.3 mm',
    'IP68',
    'Android 13',
    '2023-05-11',
    '{"4K OLED Display", "Pro Camera System", "21:9 Aspect Ratio", "Content Creation"}',
    '{"content creators", "photographers", "videographers", "professionals"}',
    '{"unique_display": true, "pro_cameras": true, "content_creation": true}'
);